repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict # No merge conflict markers
        name: No merge conflict markers
        stages: [commit]
      - id: mixed-line-ending # No mix of \n and \r\n
        name: No mixed line endings (LF and CRLF)
        stages: [commit]
      - id: no-commit-to-branch
        name: Not committing to master
        args: [--branch, master]
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        stages: [commit]
        types: [python]
        exclude: gen/

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.262
    hooks:
      - id: ruff
        args: [--fix]
        stages: [commit]
        types: [python]
        exclude: gen/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        stages: [commit]
        files: "js/"
        exclude: gen/

  - repo: local
    hooks:
      - id: npm-run-build
        name: npm-run-build
        # npm install to ensure we have the latest dependencies installed
        entry: bash -c "npm install && npm run build;"
        stages: [push]
        files: js/
        language: system
        pass_filenames: false
      - id: poetry-lock-files
        name: poetry.lock files are consistent with pyproject.toml
        entry: scripts/check_poetry_lock.py
        stages: [commit]
        files: "(pyproject.toml|poetry.lock)"
        language: system
        pass_filenames: false
      - id: mypy-all
        name: MyPy (all)
        pass_filenames: false
        files: src/
        entry: mypy src/
        stages: [push]
        language: system
      - id: pytest
        name: pytest
        stages: [push]
        language: system
        entry: bash -c "pytest"
        types: [python]
        pass_filenames: false
